//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdaniBadhaoSrabh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crop_yield_value
    {
        public int id { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Crop { get; set; }
        public double Year { get; set; }
        public string Season { get; set; }
        public double Area_Hectare { get; set; }
        public double Production_Tonnes { get; set; }
        public double Yield_Tonnes { get; set; }
        public double Yield_qa { get; set; }
        public double Yield_kg { get; set; }
    }
}
