//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdaniBadhaoSrabh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crop_calculation
    {
        public int id { get; set; }
        public string Crop_name { get; set; }
        public string Variety { get; set; }
        public string Growth_Stages { get; set; }
        public double GDD_Req { get; set; }
        public double AGDD { get; set; }
        public double Stage_Completion { get; set; }
        public double Kc { get; set; }
        public double Base__Temp { get; set; }
        public double Duration_in_Days_1 { get; set; }
        public double Cpe_ratio { get; set; }
        public double Duration_in_Days { get; set; }
        public double Cucmulative_days { get; set; }
        public double ideal_min { get; set; }
        public double ideal_max { get; set; }
        public double ideal_meanrh { get; set; }
    }
}
