//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdaniBadhaoSrabh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crop_advisory_user_response
    {
        public int id { get; set; }
        public int crope_Advisory_id { get; set; }
        public short response { get; set; }
        public string Crop_name { get; set; }
        public System.DateTime updated_on { get; set; }
        public int Irid { get; set; }
    
        public virtual user_land_by_crope user_land_by_crope { get; set; }
    }
}
