//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdaniBadhaoSrabh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crop_advisory_by_crop
    {
        public string name { get; set; }
        public int id { get; set; }
        public string DAP { get; set; }
        public string Growth { get; set; }
        public string Development { get; set; }
        public string img { get; set; }
        public string img_zoom { get; set; }
        public string icons { get; set; }
        public string Variety { get; set; }
    }
}
