//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdaniBadhaoSrabh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cropvarietystag
    {
        public int id { get; set; }
        public int CropId { get; set; }
        public int Duration { get; set; }
        public int GDD { get; set; }
        public int IWCPE { get; set; }
        public int KcFactor { get; set; }
        public int StageId { get; set; }
        public int VarietyId { get; set; }
        public int OptMax { get; set; }
        public int OptMin { get; set; }
        public int IdealRH { get; set; }
        public int PhotoperiodismId { get; set; }
    }
}
