//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdaniBadhaoSrabh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class effective_rainfal
    {
        public int id { get; set; }
        public double Rainfall { get; set; }
        public double Effective_Rainfall { get; set; }
        public double soil_layer { get; set; }
        public double soil_moisure { get; set; }
        public double Effective_Rainfall_r { get; set; }
    }
}
