//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdaniBadhaoSrabh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class map_cordinates
    {
        public int id { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public decimal Lang { get; set; }
        public int user_map_id { get; set; }
    }
}
