//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdaniBadhaoSrabh.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class amdani_badaoEntities1 : DbContext
    {
        public amdani_badaoEntities1()
            : base("name=amdani_badaoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<base_weather> base_weather { get; set; }
        public virtual DbSet<baseweather> baseweathers { get; set; }
        public virtual DbSet<crop_advisory_by_crop> crop_advisory_by_crop { get; set; }
        public virtual DbSet<crop_advisory_user_response> crop_advisory_user_response { get; set; }
        public virtual DbSet<crop_yield_value> crop_yield_value { get; set; }
        public virtual DbSet<crope> cropes { get; set; }
        public virtual DbSet<cropvarietystag> cropvarietystags { get; set; }
        public virtual DbSet<effective_rainfal> effective_rainfal { get; set; }
        public virtual DbSet<irrigation> irrigations { get; set; }
        public virtual DbSet<map_cordinates> map_cordinates { get; set; }
        public virtual DbSet<new_dcc_crop> new_dcc_crop { get; set; }
        public virtual DbSet<pesttype> pesttypes { get; set; }
        public virtual DbSet<pestweatherbaseline> pestweatherbaselines { get; set; }
        public virtual DbSet<stage> stages { get; set; }
        public virtual DbSet<statepest> statepests { get; set; }
        public virtual DbSet<stf> stfs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UpdatedWeatherAnomaly> UpdatedWeatherAnomalies { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_land_by_crope> user_land_by_crope { get; set; }
        public virtual DbSet<user_map> user_map { get; set; }
        public virtual DbSet<variety> varieties { get; set; }
        public virtual DbSet<weather> weathers { get; set; }
        public virtual DbSet<weather_master> weather_master { get; set; }
        public virtual DbSet<crop_calculation> crop_calculation { get; set; }
        public virtual DbSet<dist> dists { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<village> villages { get; set; }
    }
}
