//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdaniBadhaoSrabh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_dcc_crop
    {
        public int id { get; set; }
        public string name { get; set; }
        public string Development { get; set; }
        public double DAP { get; set; }
        public string Growth { get; set; }
        public string Suggestion { get; set; }
    }
}
