//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdaniBadhaoSrabh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pestweatherbaseline
    {
        public int id { get; set; }
        public int BaseTemp { get; set; }
        public int MaxTemp { get; set; }
        public int MeanRH { get; set; }
        public int PestTypeId { get; set; }
    }
}
