//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdaniBadhaoSrabh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stf
    {
        public string State_name { get; set; }
        public string District { get; set; }
        public Nullable<int> date_c { get; set; }
        public Nullable<decimal> Max__Temp { get; set; }
        public Nullable<decimal> Min_Temp { get; set; }
        public Nullable<decimal> Rainfall { get; set; }
        public Nullable<decimal> Mean_RH { get; set; }
        public string Mean_Temp { get; set; }
        public Nullable<decimal> p { get; set; }
        public int id { get; set; }
        public double month_c { get; set; }
        public string date_d { get; set; }
    }
}
