//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdaniBadhaoSrabh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdatedWeatherAnomaly
    {
        public int Id { get; set; }
        public Nullable<int> CropAdvisoryId { get; set; }
        public Nullable<decimal> UMinTemp { get; set; }
        public Nullable<decimal> UMaxTemp { get; set; }
        public Nullable<decimal> URainfall { get; set; }
        public Nullable<decimal> UMeanRh { get; set; }
    }
}
