//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdaniBadhaoSrabh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_map
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_map()
        {
            this.user_land_by_crope = new HashSet<user_land_by_crope>();
        }
    
        public int id { get; set; }
        public string Map_name { get; set; }
        public float Size { get; set; }
        public int User_id { get; set; }
        public string Plot_State { get; set; }
        public string Plot_District { get; set; }
        public string Plot_Taluka { get; set; }
        public string Plot_Village { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_land_by_crope> user_land_by_crope { get; set; }
    }
}
