//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdaniBadhaoSrabh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.user_map = new HashSet<user_map>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Phone_no { get; set; }
        public string Image_url { get; set; }
        public string State_Name { get; set; }
        public string Dist_Name { get; set; }
        public string Taluka_name { get; set; }
        public string Village_name { get; set; }
        public Nullable<int> Active_crope_Ad { get; set; }
        public System.DateTime User_Reg { get; set; }
        public System.DateTime Last_Active { get; set; }
        public string Home_Lat { get; set; }
        public string Home_Lang { get; set; }
        public string Language { get; set; }
        public string Email_id { get; set; }
        public string GCM_Key { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_map> user_map { get; set; }
    }
}
