//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdaniBadhaoSrabh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class weather_master
    {
        public int id { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public double date_c { get; set; }
        public double Max__Temp { get; set; }
        public double Min_Temp { get; set; }
        public double Rainfall { get; set; }
        public double Mean_RH { get; set; }
        public double Mean_Temp { get; set; }
        public double P { get; set; }
    }
}
