//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdaniBadhaoSrabh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class weather
    {
        public int id { get; set; }
        public int DistrictId { get; set; }
        public int Min { get; set; }
        public int Max { get; set; }
        public int MeanRH { get; set; }
        public int Rainfall { get; set; }
    }
}
